%YAML:1.0
#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

Camera.type: "PinHole"

Camera.fx: 303.17322
Camera.fy: 300.1103
Camera.cx: 140.05489
Camera.cy: 113.30547

# distortion parameters
Camera.k1: 0.141451
Camera.k2: -0.090218
Camera.p1: -0.014156
Camera.p2: -0.022310
Camera.k3: 0.000000

# Camera original resolution
Camera.width: 320
Camera.height: 240

# Camera frames per second
Camera.fps: 15.0

# Camera.bf: 40.0  # Set based on your baseline

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# ThDepth: 40.0
# DepthMapFactor: 1.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 500 #1000

# ORB Extractor: Scale factor between levels in the scale pyramid 
ORBextractor.scaleFactor: 1.2 #1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8 #8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20 #20
ORBextractor.minThFAST: 7 #7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
